---
- name: set cyc.properties (couchdb.user)
  lineinfile: dest=/etc/cyc.properties regexp='^couchdb.user=' line='couchdb.user={{ couchdb_user }}' create=yes mode=0644

- name: set cyc.properties (couchdb.password)
  lineinfile: dest=/etc/cyc.properties regexp='^couchdb.password=' line='couchdb.password={{ couchdb_password }}' create=yes mode=0644

- name: set cyc.properties (couchdb.host)
  lineinfile: dest=/etc/cyc.properties regexp='^couchdb.host=' line='couchdb.host={{ couchdb_host }}' create=yes mode=0644

- name: set cyc.properties (engine.host.full)
  lineinfile: dest=/etc/cyc.properties regexp='^engine.host.full=' line='engine.host.full={{ engine_host }}' create=yes mode=0644

- name: set cyc.properties (engine.host.test)
  lineinfile: dest=/etc/cyc.properties regexp='^engine.host.test=' line='engine.host.test={{ engine_host }}' create=yes mode=0644

- name: set cyc.properties (bind)
  lineinfile: dest=/etc/cyc.properties regexp='^bind=' line='bind={{ engine_bind }}' create=yes mode=0644

- name: set cyc.properties (engine.password)
  lineinfile: dest=/etc/cyc.properties regexp='^engine.password=' line='engine.password={{ engine_password }}' create=yes mode=0644
