---
- name: Installs couchdb server
  apt: pkg=couchdb state=installed update_cache=true
  notify:
    - restart couchdb

- name: Installs npm
  apt: pkg=npm state=installed update_cache=true

- name: apply fix to Ubuntu 13.10
  command: ln -s /usr/bin/nodejs /usr/bin/node creates=/usr/bin/node

- name: Install npm-couchviews
  npm: name=couchviews global=yes

- name: Is couchdb database already created?
  shell: if curl -s http://127.0.0.1:5984/cyc | grep -q "not_found" ; then echo "create" ; fi
  register: check_db
  changed_when: False

- name: create the couchdb database
  command: curl --silent -X PUT http://127.0.0.1:5984/cyc
  when: check_db.stdout == "create"

- name: create tmp-dir
  command: rm -rf /tmp/viewsToImport && mkdir /tmp/viewsToImport
  changed_when: False

- name: copy views to import
  copy: src=./ dest=/tmp/viewsToImport
  changed_when: False

- name: make sure no other files are in this directory
  command: find /tmp/viewsToImport -not -name "*.json" -type f -delete
  changed_when: False

- name: View import needed?
  shell: if [ "$(rm -rf /tmp/viewsToCompare && mkdir /tmp/viewsToCompare && couchviews dump http://127.0.0.1:5984/cyc /tmp/viewsToCompare >/dev/null && shasum /tmp/viewsToCompare/* | awk '{print $1}' | sort | shasum)" = "$(shasum /tmp/viewsToImport/* | awk '{print $1}' | sort | shasum)" ] ; then echo "no_difference" ; fi
  register: check_import
  changed_when: False

- name: import views
  command: couchviews push http://{{couchdb_user}}:{{couchdb_password}}@127.0.0.1:5984/cyc /tmp/viewsToImport
  when: check_import.stdout != "no_difference"

- name: sleep for a sec
  command: /bin/sleep 1
  changed_when: False

- name: Is an admin already created?
  shell: if curl -s http://@localhost:5984/_users/_all_docs | grep -q -v "forbidden" ; then echo "create" ; fi
  register: check_admin
  changed_when: False

- name: create an admin user
  command: curl --silent -X PUT http://127.0.0.1:5984/_config/admins/{{couchdb_user}} -d '"{{couchdb_password}}"'
  when: check_admin.stdout == "create"

- name: bind to 0.0.0.0
  lineinfile: dest=/etc/couchdb/local.ini regexp='^.?bind_address =' line='bind_address = 0.0.0.0'
  notify:
    - restart couchdb
