---
- name: Installs couchdb server
  apt: pkg=couchdb state=installed update_cache={{ apt_update_cache }}
  notify:
    - restart couchdb

- name: Installs npm
  apt: pkg=npm state=installed update_cache={{ apt_update_cache }}

- name: apply fix to Ubuntu 13.10
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Install npm-couchviews
  npm: name=couchviews global=yes

- name: bind to 0.0.0.0
  lineinfile: dest=/etc/couchdb/local.ini regexp='^.?bind_address =' line='bind_address = 0.0.0.0'
  when: couchdb_multi_server
  notify:
    - restart couchdb

- name: allow to authenticated users only
  lineinfile: dest=/etc/couchdb/local.ini regexp='require_valid_user = (true|false)+' line='require_valid_user = true'
  when: couchdb_multi_server
  notify:
    - restart couchdb
