---
- name: Installs Java7
  apt: pkg=default-jre-headless state=installed update_cache=true

- name: Installs sysv-rc-conf package to manage runlevel config
  apt: pkg=sysv-rc-conf state=installed update_cache=true

- name: copy engine-container
  copy: src=cyc-engine-container dest=/usr/local/

- name: create logs
  command: mkdir -p /usr/local/cyc-engine-container/logs

- name: copy start/stop script
  copy: src=scripts/cyc-engine-container dest=/etc/init.d/cyc-engine-container mode=0755

- name: create security.policy for a config under /etc/cyc.properties
  copy: src=cyc-engine-container/security.policy dest=/etc/cyc-security.policy
  notify:
    - restart cyc-engine-container

- name: add permission to read the config file
  lineinfile: dest=/etc/cyc-security.policy line='grant { permission java.io.FilePermission "/etc/cyc.properties", "read"; };'
  notify:
    - restart cyc-engine-container

- name: add socket permission (listen)
  lineinfile: dest=/etc/cyc-security.policy regexp='permission java.net.SocketPermission "localhost",.*resolve' line='permission java.net.SocketPermission "localhost", "resolve,listen";'
  notify:
    - restart cyc-engine-container

- name: add socket permission (from WEB)
  lineinfile: dest=/etc/cyc-security.policy regexp='permission java.net.SocketPermission ".*:-", "accept,resolve";' line='permission java.net.SocketPermission "{{groups['web'][0]}}:-", "accept,resolve";'
  notify:
    - restart cyc-engine-container

- name: add socket permission (to DB)
  lineinfile: dest=/etc/cyc-security.policy regexp='permission java.net.SocketPermission ".*:5984", "connect,resolve";' line='permission java.net.SocketPermission "{{groups['db'][0]}}:5984", "connect,resolve";'
  notify:
    - restart cyc-engine-container

- name: auto start
  command: sysv-rc-conf cyc-engine-container on


