---
- hosts: localhost
  connection: local
  tasks:
    - name: create (or get) a cloud VM
      digital_ocean: >
        id=1298781
        ssh_key_ids=94992,94782
        state=present
        command=droplet
        name=cyc-vm-1
        size_id=66
        region_id=5
        image_id=1505699
        wait_timeout=500
      register: new_droplet
    - debug: msg="ID is {{ new_droplet.droplet.id }}"
    - debug: msg="IP is {{ new_droplet.droplet.ip_address }}"
    - name: create inventory file
      template: src="digitalocean.j2" dest="{{ ansible_env.PWD }}/digitalocean" mode="0644"
    - name: create DNS
      digital_ocean_domain: >
        state=present
        name={{ new_droplet.droplet.name }}.zimperium.de
        ip={{ new_droplet.droplet.ip_address }}
        id={{ new_droplet.droplet.id }}
      
