---
- name: Installs tomcat7 web server
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - tomcat7
    - tomcat7-admin
  notify:
    - restarted tomcat7

- name: copy server config
  copy: src=server.xml dest=/etc/tomcat7/server.xml
  notify:
    - restarted tomcat7

- name: allow bind to port 80
  lineinfile: dest=/etc/default/tomcat7 regexp='^.?AUTHBIND=' line='AUTHBIND=yes'
  notify:
    - restarted tomcat7

- name: pass game-engine property file to tomat
  lineinfile: dest=/etc/default/tomcat7 line="JAVA_OPTS=\"${JAVA_OPTS} -Dcyc.properties=/etc/cyc.properties\""
  notify:
    - restarted tomcat7

- name: add user to tomcat-users-xml
  lineinfile: dest=/etc/tomcat7/tomcat-users.xml regexp="<user username=\"manager\" password.*" line="<user username=\"manager\" password=\"{{ lookup('env','TOMCAT_MANAGER_PASSWORD') }}\" roles=\"manager-gui\"/>" insertbefore="</tomcat-users>"
  when: lookup('env','TOMCAT_MANAGER_PASSWORD') is defined
  notify:
    - restarted tomcat7
