---
- name: Installs tomcat7 web server
  apt: pkg={{ item }} state=installed update_cache={{ apt_update_cache }}
  with_items:
    - tomcat7
    - tomcat7-admin
  notify:
    - restarted tomcat7

- name: copy server config
  copy: src=server.xml dest=/etc/tomcat7/server.xml
  when: tomcat_standalone
  notify:
    - restarted tomcat7

- name: allow bind to port 80
  lineinfile: dest=/etc/default/tomcat7 regexp='^.?AUTHBIND=' line='AUTHBIND=yes'
  when: tomcat_standalone
  notify:
    - restarted tomcat7

- name: pass game-engine property file to tomat
  lineinfile: dest=/etc/default/tomcat7 line="JAVA_OPTS=\"${JAVA_OPTS} -Dcyc.home=/usr/local/cyc-engine-container -Dcyc.properties=/etc/cyc.properties\""
  notify:
    - restarted tomcat7

- name: change umask
  lineinfile: dest=/etc/default/tomcat7 line="umask 0002"
  notify:
    - restarted tomcat7

- name: add user to tomcat-users-xml
  lineinfile: dest=/etc/tomcat7/tomcat-users.xml regexp="<user username=\"manager\" password.*" line="<user username=\"manager\" password=\"{{ lookup('env','TOMCAT_MANAGER_PASSWORD') }}\" roles=\"manager-gui\"/>" insertbefore="</tomcat-users>"
  when: lookup('env','TOMCAT_MANAGER_PASSWORD') is defined
  notify:
    - restarted tomcat7

- name: check if user cyc-engine exists
  command: grep -q '^cyc-engine' /etc/passwd
  register: check_cyc_engine_user
  changed_when: False
  ignore_errors: True
  failed_when: False 

- name: add user cyc-engine to group tomcat7
  user: name=cyc-engine groups=tomcat7
  when: check_cyc_engine_user.rc == 0

## haproxy config

- name: set haproxy-config
  lineinfile: dest=/etc/default/haproxy regexp='^ENABLED=' line='ENABLED=1'
  when: tomcat_standalone == False
  notify: restart haproxy

- lineinfile: dest=/etc/haproxy/haproxy.cfg line='    acl is_cyr_oglimmer  hdr_end(host) -i cyr.oglimmer.de' insertbefore='#START-CUSTOM-OF-FRONTEND-CONFIG'
  when: tomcat_standalone == False
  notify: restart haproxy

- lineinfile: dest=/etc/haproxy/haproxy.cfg line='    use_backend tomcat          if is_cyr_oglimmer' insertafter='#START-CUSTOM-OF-FRONTEND-CONFIG'
  when: tomcat_standalone == False
  notify: restart haproxy


